# Generated by Django 3.1.6 on 2021-07-27 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='TITLE')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE PUBLISHED')),
                ('body', models.TextField(default='', verbose_name='CONTENT')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communitys',
                'db_table': 'community_posts',
                'ordering': ('-mod_date',),
            },
        ),
    ]
